[package]
cairo-version = "2.12.2"
name = "survivor_valhalla"
version = "1.7.1"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate"
spawn = "sozo execute survivor_valhalla-actions spawn --wait"
move = "sozo execute survivor_valhalla-actions move -c 1 --wait"

[dependencies]
dojo = { path = "vendor/dojo" }
starknet = "2.12.2"
beasts_nft = { path = "vendor/beasts_nft" }
openzeppelin_token = { path = "vendor/openzeppelin_token" }

[patch."https://scarbs.xyz"]
snforge_std = { path = "vendor/snforge_std" }
dojo = { path = "vendor/dojo" }
dojo_cairo_macros = { path = "vendor/dojo_cairo_macros" }
openzeppelin_token = { path = "vendor/openzeppelin_token" }
openzeppelin_access = { path = "vendor/openzeppelin_access" }
openzeppelin_account = { path = "vendor/openzeppelin_account" }
openzeppelin_introspection = { path = "vendor/openzeppelin_introspection" }
openzeppelin_utils = { path = "vendor/openzeppelin_utils" }

[[target.starknet-contract]]
build-external-contracts = [
    "dojo::world::world_contract::world",
    "beasts_nft::beasts_nft"
    ]

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros"]

[dev-dependencies]
cairo_test = "2.12.2"

[profile.mainnet]

[profile.sepolia]
