name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'contract/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'contract/**'
      - '.github/workflows/ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build contracts
      working-directory: ./contract
      run: |
        docker run --rm \
          --platform linux/arm64 \
          -v ${{ github.workspace }}/contract:/app \
          -w /app \
          ghcr.io/dojoengine/dojo:v1.7.1 \
          sozo build
    
    - name: Run tests
      working-directory: ./contract
      run: |
        docker run --rm \
          --platform linux/arm64 \
          -v ${{ github.workspace }}/contract:/app \
          -w /app \
          ghcr.io/dojoengine/dojo:v1.7.1 \
          sozo test